title: INF-3201 Parallel Programming (Fall 2020)

description: >
  INF-3201 Parallel Programming, fall 2020, University of Tromsø. 

contact:
  email: jmb@cs.uit.no
  name: John Markus Bjørndalen

baseurl: ""
markdown: kramdown
